# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_management_db
spring.datasource.username=postgres
spring.datasource.password=adm27646
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.datasource.hikari.auto-commit=false

# ===============================
# SERVER SETTINGS
# ===============================
server.port=3000

# ===============================
# EMAIL SETTINGS (MOCK MODE)
# ===============================
# We comment these out so the app doesn't try to connect to Google.
# The EmailService will print to the console instead.
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=adamannouridriss@gmail.com
# spring.mail.password=Idriss,6629
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# SECURITY (JWT)
# ===============================
# JWT Secret Key (Fixed so it works after restart)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Token Expiration (24 hours)
jwt.expiration=86400000